lastModDate = new Date(document.lastModified)
if (lastModDate.valueOf() < 0)
  lastModDate.setMilliseconds(2212108096000)
today = new Date()

document.write('<hr>')
document.write('<table width="100%" summary="footer" cellspacing="0" cellpadding="0">')
document.write('  <tr>')
document.write('    <td align="LEFT"><a href="javascript:window.scroll(0,0)">Top of Page<\/a><\/td>')
document.write('    <td align="RIGHT"><\/td>')
document.write('  <\/tr>')
document.write('  <tr>')
document.write('    <td align="LEFT">')
document.write('      Revised ' + lastModDate.toUTCString())
document.write('    <\/td>')
document.write('    <td align="RIGHT">URL: <a href="http:\/\/www.brucelindbloom.com">http:\/\/www.brucelindbloom.com<\/a><\/td>')
document.write('  <\/tr>')
document.write('  <tr>')
document.write('    <td colspan="2" align="CENTER">All material on this web site is Copyright &copy; 2001 - ' + today.getFullYear() + ' Bruce Justin Lindbloom. All Rights Reserved.<\/td>')
document.write('  <\/tr>')
document.write('<\/table>')
